name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        distutils:
        - stdlib
        - local
        python:
        - pypy-3.7
        - 3.7
        - 3.9
        - "3.10"
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.platform }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        run: tox -- -n auto --cov-report xml
      - name: Publish coverage
        if: false  # disabled for #2727
        uses: codecov/codecov-action@v1
        with:
          flags: >-  # Mark which lines are covered by which envs
            ${{ runner.os }},
            ${{ matrix.python }}

  test_cygwin:
    strategy:
      matrix:
        distutils:
        - stdlib
        - local
    runs-on: windows-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Cygwin with Python and tox
        run: |
          choco install git gcc-core python38-devel python38-pip --source cygwin
          C:\\tools\\cygwin\\bin\\bash -l -x -c 'python3.8 -m pip install tox'
      - name: Run tests
        run: |
          C:\\tools\\cygwin\\bin\\bash -l -x -c 'cd $(cygpath -u "$GITHUB_WORKSPACE") && tox -- -n auto --cov-report xml'

  release:
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
